### Create
POST http://localhost:3000/dishes
Content-Type: application/json

{
  "name": "Pasta with ingredients",
  "description": "Pasta description 2",
  "isPublic": true,
  "ingredients": [
    {
      "productId": 2,
      "amount": 3
    }
  ]
}

### Get all
GET http://localhost:3000/dishes

### Get one by id
GET http://localhost:3000/dishes/3

### Update
PUT http://localhost:3000/dishes/3
Content-Type: application/json

{
  "id": 3,
  "name": "Cośtam",
  "description": "Pasta with tomato sauce",
  "servings": 3
}

### Delete
DELETE http://localhost:3000/dishes/1

