### Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Pasta",
  "unit": "kg",
  "amount": 1
}

### Get all
GET http://localhost:3000/products

### Get one by id
GET http://localhost:3000/products/1

### Update
PUT http://localhost:3000/products/1
Content-Type: application/json

{
  "id": 1,
  "amount": 2
}

### Delete
DELETE http://localhost:3000/products/1

