### Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Sugar",
  "unit": "kg"
}

### Get all
GET http://localhost:3000/products

### Get one by id
GET http://localhost:3000/products/1

### Update
PUT http://localhost:3000/products/3
Content-Type: application/json

{
  "name": "Sugar2"
}

### Delete
DELETE http://localhost:3000/products/1

